import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const montserrat = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Surdma Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-mont bg-light w-full min-h-screen flex flex-col justify-between`}
      >
        <Navbar />
        <div className="h-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
